spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa.properties.hibernate:
    show_sql: true
    use_sql_comments: true
    format_sql: true
